[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify"
  
[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing and API endpoints
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

# Force all unmatched routes through our SvelteKit app
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/render"
  status = 200 